#!/bin/sh

export CVS_RSH=ssh

dirs="clip prg cliplibs"
pwd=`pwd`

for dir in $dirs
do
	cvs -z 9 -d:pserver:anonymous@clip-itk.cvs.sourceforge.net:/cvsroot/clip-itk checkout -P $dir

	if [ -f $dir/CVS/Template ]
	then
		echo $USER >>$dir/CVS/Template
	fi

done
