
#ifndef _COLOR_DEFINED

#define COLOR_STANDARD    0
#define COLOR_ENHANCED    1
#define COLOR_BORDER      2
#define COLOR_BACKGROUND  3
#define COLOR_UNSELECTED  4
#define CLR_STANDARD    COLOR_STANDARD
#define CLR_ENHANCED    COLOR_ENHANCED
#define CLR_BORDER      COLOR_BORDER
#define CLR_BACKGROUND  COLOR_BACKGROUND
#define CLR_UNSELECTED  COLOR_UNSELECTED


#define _COLOR_DEFINED
#endif

