CC= gcc
CFLAGS = -O -g -Wall -Wextra -fPIC
OBJS = ../coll.o ../list.o ../hash.o
PTH_LIBS= -lpth
PTH_TEST= pth_tst
LIBOBJS = pth_task.o
LIB = task.a

all: $(LIB)

$(LIB): $(LIBOBJS)
	rm -f $(LIB)
#	ar -r $(LIB) $(LIBOBJS) $(PTH_LIBS)
	../clip_makelib $(LIB) $(LIBOBJS) 
	ranlib $(LIB)

pth_task.c: task.h 
	$(CC) -c pth_task.c -o pth_task.o $(PTH_LIBS)

task_tst: $(OBJS) task_tst.o $(LIB)
	$(CC) $(CFLAGS) task_tst.c -o task_tst $(OBJS) $(LIB) $(PTH_LIBS)

std_tst: pth_tst
pth_tst: pth_tst.c
	$(CC) pth_tst.c -o pth_tst $(PTH_LIBS)
clean: 
	cp Makefile.empty Makefile
	rm -f $(PTH_TEST) task_tst
	rm -f USE*
	rm -f *.o *.bak
