LIB = task.a
PROGS = cl_tst
PTH_TEST= pth_tst

all: 
clean:
	rm Makefile
	rm -f $(LIB) $(PROGS) *.o core *.bak *.BAK *.a
	rm -f cl_cfg.h
	rm -f $(PTH_TEST) task_tst cl_tst pth_tst
	rm -f USE*
	cp Makefile.empty Makefile
