CLIP	= $(CLIPROOT)/bin/clip
CLIPFLAGS = -a -O -b -w
#CLIPLIBS  = ../libclip-codb.so
CLIPLIBS  = -lclip-codb
.SUFFIXES: .prg .o .po
PROGS =

all: $(PROGS)

clean:
	rm -rf *.exe *.uri *.c *.o *.a *.so *.po *.log *.pa *.b \
	*.BAK *.bak *~ core* *core *.ex *.nm

